In [1]:
import numpy as np

X = np.array([[2, 9], [1, 5], [3, 6]], dtype=float)
y = np.array([[92], [86], [89]], dtype=float)
X = X / np.amax(X, axis=0) # Normalizing X array longitudinally
y = y / 100 # Scaling target values

print(X)
print(y)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

epoch = 5 # Setting training iterations
lr = 0.1 # Setting learning rate

inputlayer_neurons = 2 # Number of features in dataset
hiddenlayer_neurons = 3 # Number of hidden layer neurons
output_neurons = 1 # Number of neurons at output layer

# Initializing weights and biases
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons)) # Hidden layer weights
bh = np.random.uniform(size=(1, hiddenlayer_neurons)) # Hidden layer bias
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons)) # Hidden-output weights
bout = np.random.uniform(size=(1, output_neurons)) # Hidden-output bias

for i in range(epoch):
    # Forward Propagation
    hinp1 = np.dot(X, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid(hinp) # Activation

    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1 + bout
    output = sigmoid(outinp) # Activation

    # Backpropagation
    EO = y - output # Error
    outgrad = derivatives_sigmoid(output)
    d_output = EO * outgrad

    EH = d_output.dot(wout.T) # How much hidden layer weights contributed to error
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

    # Updating weights and biases
    wout += hlayer_act.T.dot(d_output) * lr # Dot product of next layer error and current layer output
    wh += X.T.dot(d_hiddenlayer) * lr

    print("---------Epoch-", i + 1, "Starts---------")
    print("Input: \n", X)
    print("Actual Output: \n", y)
    print("Predicted Output: \n", output)
    print("---------Epoch-", i + 1, "Ends---------\n")

print("Input: \n", X)
print("Actual Output: \n", y)
print("Predicted Output: \n", output)


[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
---------Epoch- 1 Starts---------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.71589617]
 [0.70302747]
 [0.71658351]]
---------Epoch- 1 Ends---------

---------Epoch- 2 Starts---------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.71976836]
 [0.70660563]
 [0.72039844]]
---------Epoch- 2 Ends---------

---------Epoch- 3 Starts---------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
 [[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.72349996]
 [0.71005794]
 [0.72407514]]
---------Epoch- 3 Ends---------

---------Epoch- 4 Starts---------
Input: 
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Ou